### ISSUE TITLE
Editting a wiki page doesn't work

### ISSUE THREAD

**Issue by bhyde** [xthexder/wide-github#11]
I get this
![image](https://cloud.githubusercontent.com/assets/19701/8877115/cef26cae-31f1-11e5-980f-b1753c21d08e.png)

which hides the beginning of each line.

**Comment by xthexder** [comment]
What browser / verison are you using? I'm unable to reproduce this in either Firefox 38 or Chrome 43.
That looks like the emoji suggestion box. Were you in the middle of typing something, or is it always there?

**Comment by bhyde** [comment]
Good news.  It's "Github Comment Enhancer", so not your fault.  :)
