### ISSUE TITLE
wide-github doesn't work on gists

### ISSUE THREAD

**Issue by wlk** [xthexder/wide-github#12]
wide-github doesn't work on gists (I think it could and should), example of a gist: https://gist.github.com/kermitas/a19a89003a50a1812e4f

**Comment by xthexder** [comment]
I think this should definitely be a feature, I'll take a look at implementing it when I get a chance.

**Comment by xthexder** [comment]
The latest version 1.1.0 now works on gists. I'll have it updated on the Chrome Store soon.

**Comment by wlk** [comment]
Thanks, I'm using version from Chrome Store and it's working OK
