### ISSUE TITLE
Make CSS compatible with Stylish/UserStyles.org

### ISSUE THREAD

**Issue by BenBE** [xthexder/wide-github#15]
Would be nice to have the wide-github.css file available in a format suitable for direct import into Stylish/UserStyles.org (at least for everything that doesn't require JS to be executed).

**Comment by Martii** [comment]
Btw... https://bugzilla.mozilla.org/show_bug.cgi?id=1472948

This extension of Stylish has been blocked in Fx 61.0.1 as of July 4th, 2018.
