### ISSUE TITLE
Support new Github Layout in Firefox

### ISSUE THREAD

**Issue by plumdog** [xthexder/wide-github#16]
Github has a new layout, and the widening appears not to play nicely.

Currently being rolled out, see: https://github.com/blog/2085-a-new-look-for-repositories

(Appears to be fine in Chrome though.)

**Comment by plumdog** [comment]
Eg:
![2015-11-19-124553_1902x1182_scrot](https://cloud.githubusercontent.com/assets/2348591/11271063/94f2bec4-8ebb-11e5-99da-106cef6a729c.png)

**Comment by xthexder** [comment]
Unfortunately I'm not currently getting the option to opt in to the new layout yet, so this will have to wait until I can test it.

Feel free to make a PR in the mean time.

**Comment by xthexder** [comment]
Sorry I mistaken, the prompt just showed up now.

Are you sure you're on the latest version of the script? The new layout seems to work fine in both Firefox and Chrome for me.

**Comment by plumdog** [comment]
Ah, yes, you're quite right - updating fixed it.
Thanks!
