### ISSUE TITLE
Comments buttons unreachable when long lines are in the diff

### ISSUE THREAD

**Issue by skyjur** [xthexder/wide-github#17]
When code diff contains long lines comment form becomes very tedious to use:

![selection_219](https://cloud.githubusercontent.com/assets/321391/15015623/f1dc99ee-1204-11e6-8955-75fbee1da027.png)

**Comment by Martlark** [comment]
Just having this issue.  Rather annoying!

**Comment by xthexder** [comment]
Fixed in 1.2.0
