### ISSUE TITLE
An option to enable / disable it?

### ISSUE THREAD

**Issue by bibstha** [xthexder/wide-github#21]
Sometimes reading wikis, everything is very long and I wish I could quickly switch back to original layout.
Can you add an option to click on the icon to enable / disable it temporarily?

**Comment by jamiebrynes7** [comment]
I've opened a PR to address the lack of toggling: https://github.com/xthexder/wide-github/pull/29

**Comment by xthexder** [comment]
Added to the 1.4.0 version of the Chrome Extension.
