### ISSUE TITLE
Userscript doesn't work in Edge + Tampermonkey

### ISSUE THREAD

**Issue by aggieben** [xthexder/wide-github#30]
There aren't any errors or anything in the dev console, it just doesn't work.  Unsure why.

**Comment by Martii** [comment]
@aggieben 

Finally was able to update to 1803 of Win10 *(buggy windows update as usual for months and 6th time I've tried... Version 1803 (OS Build 17134.112))*... and got this in the console of Developer Tools regarding this script:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
```

```
Tampermonkey v4.6.5757
```

``` console
Syntax error @ "Wide Github"!
##########################
JSHINT output:
##########################

EvalError: Blocked by Content Security Policy
   at Anonymous function (Unknown script code:2:487)
   at b (Unknown script code:1:403)
   at fa.E_u (Unknown script code:3:138)
   at Anonymous function (Function code:61:96)
   at ka (Function code:59:371)
   at create (Function code:70:334)
   at e (Function code:14:154)

 SCRIPT5: SCRIPT5: Blocked by Content Security Policy
```

Note: Earlier versions of Edge won't tell you squat.

This is most likely a probable Tampermonkey and/or a possible Edge issue. Cc: @derjanb I literally can't see anything off the bat that this script does that is unusual. Even tried a simpler metadata block and a fork of it... still didn't run... but CSP could be a factor... although doesn't explain why it runs well in Moz and Chromium based browsers.

**Comment by xthexder** [comment]
It looks like this is a bug in Edge itself: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11320214/
There's not really much I can do from the extension / js side.

**Comment by xthexder** [comment]
This is now fixed in the latest Edge / Tampermonkey versions.
