### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by edenman** [xthexder/wide-github#43]
I love this extension, thanks!  Seems like maybe they changed something about their html?  I tried re-installing the extension to no avail.  Mojave running Chrome 72.0.3626.109, non-enterprise Github account.

**Comment by xthexder** [comment]
It looks like Github was updated some time in the last ~30 minutes. I'm looking into it, and I'll see if I can get an updated release out tonight.

**Comment by SirUppyPancakes** [comment]
Same.
Windows 10 x64 + Chrome Version 72.0.3626.109 (Official Build) (64-bit)

Looks like `container-lg` is somehow not having it's `max-width` set to `none`.

**Comment by xthexder** [comment]
`.container` was changed to `.container-lg`
Should be a simple fix, but it will be a little bit until I can get the Chrome plugin updated.

**Comment by xthexder** [comment]
Well, at least for me, it seems like Github reverted whatever change they made.
I'll still make an update so the plugin should work on either version.

**Comment by Martii** [comment]
@xthexder 

> Looks like container-lg is somehow not having it's max-width set to none.

This seems highly related to [an issue on OUJS](https://openuserjs.org/garage/Code_works_inside_of_the_console_but_not_the_script). I'm in PM right now and the .user.js appears to be working. Was there a specific page that it wasn't working on?

**Comment by Martii** [comment]
Here's Linux with the 3b35d5cdb5662aa38133f1efd4dfb2cb570dd372 .user.js in Chrome. *(With Chromium I'm using the Stylus CSS... it too seems to be working atm)*:

<a href="https://user-images.githubusercontent.com/114709/53140319-8d3d4b80-3549-11e9-91ba-b60e7507d6a4.png"><img src="https://user-images.githubusercontent.com/114709/53140319-8d3d4b80-3549-11e9-91ba-b60e7507d6a4.png" alt="Chrome Clean Profile Screencap" title="Click to enlarge... Chrome Clean Profile Screencap" width="168" height="105"/></a>
