### ISSUE TITLE
makejs.js incorrectly building userscript but builds user.css without issue

### ISSUE THREAD

**Issue by CollinChaffin** [xthexder/wide-github#44]
Very frustrating that the makecss.js is fine and the makejs.js for some reason refuses to generate the file properly due to it changing line breaks to unix LF but since it's during conversion they are embedded hence cannot simply have the file converted.  Basically from what I can tell the parser in the makejs needs to be revisited when run on Windows node.

**Comment by CollinChaffin** [comment]
I'll close this but to save a bunch of hair-pulling please leave it here for future seekers.  Node when building using this parsing IN COMBINATION with Git config on Windows of `git config --global core.autocrlf true` will actually result in this case of the css being just fine and only the user.js having embedded `^M` (NOT at the EOL where they can be converted).

So, to build on Windows you MUST first change this option to `git config --global core.autocrlf false` in which case you will no longer receive this warning that actually appears to come from the Node build:

```
warning: LF will be replaced by CRLF The file will have its original line endings in your working directory.........
```

So, in this case I had to change the option, completely roll out my commit - re-pull all sources ensuring the source CSS I was starting with had NOT had it's EOL's converted, then and only then does the JS build fine along with the generated user.css.

**Comment by Martii** [comment]
See https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

**Comment by xthexder** [comment]
I've fixed this so the script should always strip CRLF and generate a single LF character.
