### ISSUE TITLE
Install with userContent.css

### ISSUE THREAD

**Issue by SoniEx2** [xthexder/wide-github#46]
The README should say that you can just stick the CSS into userContent.css and it works.

**Comment by Martii** [comment]
@SoniEx2 

> userContent.css

That particular feature may be going away eventually in Moz browsers.

**Comment by SoniEx2** [comment]
well, it works, and doesn't require me to install malware to get this thing to work.

besides, if more ppl talk about it, it's less likely to get removed.

**Comment by Martii** [comment]
@SoniEx2 

> doesn't require me to install malware to get this thing to work.

Think you better justify that statement. It seems you are mixing up all the known .user.js engines and Stylus vs Stylish. Might want to do some more research before making a blanket assumption without citation. :smiley:

**Comment by Martii** [comment]
Additional item...

>  CSS into userContent.css and it works.

Applies to all websites which is a very bad thing.

**Comment by SoniEx2** [comment]
`@-moz-document regexp("^https://(?:gist\\.)?github\\.com/.*") {`, https://github.com/xthexder/wide-github/blob/master/build/wide-github.user.css#L16

**Comment by Martii** [comment]
That is located in the .user.css not the CSS *(I wrote that portion so I know the nomeclature)*. Clarity is important in your issue description. Dropping the CSS into userContent.css will absolutely, and unequivicably run on all sites. :smile: 

Anyhow... you are welcome to do a PR. I've stated some reasons why it should probably not be in there. Xthexder will decide if it is agreeable to merge. I'm still looking for your validation of the "malware" statement. Clearly that is unsubstantiated atm. You still have the choice to not use it as a Chrome/Chromium extension, .user.js, or .user.css.

**Comment by SoniEx2** [comment]
the userstyles extension was malware so I'm not touching anything like it ever.

otoh that line prevents the CSS from running on every page. it makes it only run on github. yes, that specific line still runs on every page but w/e so would the equivalent line of the extension.

**Comment by Martii** [comment]
Here we go:

`toolkit.legacyUserProfileCustomizations.stylesheets` in Fx 69.x forward... it's on its way out.

Refs:
* https://www.mozilla.org/en-US/firefox/69.0/releasenotes/
* https://www.ghacks.net/2019/09/03/firefox-69-0-release-information/

**Comment by SoniEx2** [comment]
That's a reason to start *aggressively* using it, so they keep it and improve the UX.
