### ISSUE TITLE
Feature Preview "Repository Refresh" Breaks functionality

### ISSUE THREAD

**Issue by Bilibox** [xthexder/wide-github#53]
As the title states the Feature Preview "Repository Refresh" Breaks the scripts functionality. 

Functionality should be added for the new style

**Comment by joakime** [comment]
The new github style is now official.
This extension needs an update.

**Comment by joakime** [comment]
Looks like PR #54 is a fix for this issue.

**Comment by unixfox** [comment]
Temporary fix until #54 get merged:
1. Install the extension Greasemonkey (Firefox) or Tampermonkey (Chrome)
2. Install the user script by clicking on this url: https://github.com/amirmeimari/wide-github/raw/master/build/wide-github.user.js

**Comment by xthexder** [comment]
The extension is now updated for the "Repository Refresh" in version 1.4.2
The Chrome Extension will take a little while to publish, since apparently they have started manually reviewing permissions settings.
The User Scripts / Greasemonkey versions are up to date now is master.
