### ISSUE TITLE
manifest "licenses" key no longer recognized

### ISSUE THREAD

**Issue by joakime** [xthexder/wide-github#55]
The "licenses" key in the manifest.json for Chrome extensions is no longer recognized.

See documentation of keys at https://developer.chrome.com/extensions/manifest

The existence of this key results in an error in the Extensions dialog.

![wide-github-extension-installed](https://user-images.githubusercontent.com/191721/85437032-941a0b00-b54f-11ea-8cfc-aa8d528fbf79.png)

![wide-github-extension-error](https://user-images.githubusercontent.com/191721/85437036-967c6500-b54f-11ea-96ab-982811cd16f6.png)

**Comment by xthexder** [comment]
I've removed the licenses manifest key in master. The LICENSE file is still included in the zip and linked to in the user.js / user.css scripts.
