### ISSUE TITLE
Has stopped working with latest github interface update

### ISSUE THREAD

**Issue by ANTGOMEZ** [xthexder/wide-github#56]
Not sure if this project is still being worked on but it has stopped working with the latest release of GitHub interface. I noticed today that GitHub interface was updated but the page is no longer wide, which the plugin would set.

**Comment by geoff2k** [comment]
https://github.com/xthexder/wide-github/pull/54 fixes the issue. :)

**Comment by ANTGOMEZ** [comment]
how do I get the update?

**Comment by Nex4rius** [comment]
Try <a href="https://raw.githubusercontent.com/xthexder/wide-github/master/build/wide-github.user.js">this</a>

**Comment by xthexder** [comment]
Version 1.4.3 has been published to the Chrome Web Store

**Comment by ANTGOMEZ** [comment]
you rock, so hard!
