### ISSUE TITLE
please release the latest extension to the chrome web store

### ISSUE THREAD

**Issue by fawaf** [xthexder/wide-github#57]

**Comment by xthexder** [comment]
I submitted the update, but they changed their policy. It was denied because apparently it's missing an icon. I've got to make one now, but I don't have a lot of time.

**Comment by jackred8** [comment]
@xthexder Please, you have a lot of users, thanks mate.

**Comment by geoff2k** [comment]
@xthexder like many of us, I'm sure you probably have a lot competing for your time in these times of pandemic, so just wanted to chime in that we appreciate the work you do and your responsiveness so far. 👍 

Seems to me that those that _absolutely_ need the fix sooner could probably learn to use Greasemonkey/Tampermonkey to run the script version and don't **have** to wait for the extension to be added to the store...

**Comment by xthexder** [comment]
I've submitted another update with icons added. Hopefully it will be available soon and I'm not still missing something.

**Comment by xthexder** [comment]
Version 1.4.3 has been published to the Chrome Web Store
