### ISSUE TITLE
possible to release firefox plugin as well?

### ISSUE THREAD

**Issue by fawaf** [xthexder/wide-github#58]
i've tested it in firefox and it seems to work.

yay WebExtension

**Comment by xthexder** [comment]
I haven't looked into Firefox extensions much before, The WebExtension API wasn't around yet when I started this, I'll definitely look into it.

**Comment by xthexder** [comment]
I just submitted this to the Mozilla Addons page, and it's now available in Firefox: https://addons.mozilla.org/en-US/firefox/addon/wide-github-chrome/
