### ISSUE TITLE
Repo menu not widened 

### ISSUE THREAD

**Issue by mimecry** [xthexder/wide-github#64]
Hi, thank you for this addon. Is it possible to have the repo menu aligned to the left as well? instead of this

![image](https://user-images.githubusercontent.com/10742312/100890862-47b5fc80-34eb-11eb-894d-891581df7d8d.png)

it should look like this: 
![image](https://user-images.githubusercontent.com/10742312/100891186-982d5a00-34eb-11eb-9ee9-3e86004932c7.png)

**Comment by xthexder** [comment]
This menu is full-width on the default site and wide-github shouldn't be changing any styling related to it. In your screenshot, the right side of the menu is correctly aligned, which is odd.

Do you have any other extensions installed that might be conflicting? The only other thing I can think of is maybe GitHub is testing out some new styling changes, but I'm not seeing this issue on any of my PCs.

**Comment by mimecry** [comment]
you're right, it's a feature of Refined Github, as confirmed by the repo description. funny thing is that it is hardcoded, so there is no option to revert this in the settings, which is why i overlooked it as a possible culprit when i was combing through its options earlier. i'll file the appropriate bug report to the Refined Github repo.
