### ISSUE TITLE
Misaligned Assignee dropdown and avatar in issues/PR list

### ISSUE THREAD

**Issue by Strum355** [xthexder/wide-github#65]
Screenshot highlights the issue. Avatar isnt aligned with the proper dropdown

![image](https://user-images.githubusercontent.com/18282288/110795479-ccdd4a00-826e-11eb-8d01-1d19cdf8cac6.png)

Without wide github:
![image](https://user-images.githubusercontent.com/18282288/110795565-e54d6480-826e-11eb-800b-110251a740bc.png)

**Comment by xthexder** [comment]
Fixed in version 1.4.4.
The update has been submitted to the Chrome and Mozilla web stores, and will be available there after review. The user script is available immediately.

Thanks for the bug report!
