### ISSUE TITLE
Can't click right sidebar in issues

### ISSUE THREAD

**Issue by getaaron** [xthexder/wide-github#7]
As of a few days ago, I can't edit the right sidebar while this extension is enabled:

![image](https://cloud.githubusercontent.com/assets/789577/6924177/3c22fa1a-d79c-11e4-999d-2a97ff9bad78.png)

None of these elements are clickable, but they work fine if I disable wide-github.

**Comment by getaaron** [comment]
Possibly related to https://github.com/xthexder/wide-github/commit/e0b8a2cf88433c9c12d47de456a0d4f459145403?

**Comment by xthexder** [comment]
I can't seem to reproduce this in my version of Firefox / Greasemonkey.
Could you confirm the issue doesn't exist in the commit before? [You can find it here.](https://github.com/xthexder/wide-github/blob/1793b59afbe9a99a34e7c63ac58e9399421f6f75/wide-github.user.js)

I'm using this issue to test, so if it isn't happening on this issue, can you link me to one that does?

**Comment by xthexder** [comment]
Version 1.0.11 should fix the problem. It should be published on the Chrome Web Store soon for you to confirm.

**Comment by getaaron** [comment]
Thanks. I'll check it out. Sorry I didn't mention my browser in the initial note.

**Comment by getaaron** [comment]
Version 1.0.11 resolves this. Thanks for the fast update!
