### ISSUE TITLE
Issues View doesn't look right

### ISSUE THREAD

**Issue by mustaphazorgati** [xthexder/wide-github#74]
Hi there!

First of all: I love the idea behind this plugin! :) 

Unfortunately wide-github does not align the icons within GitHub issues correctly. I have provided a screenshot of the issue. Top browser: wide-github. Bottom browser: default.

![Screenshot from 2023-03-22 03-31-23](https://user-images.githubusercontent.com/15628173/226787307-6d0cecff-a294-443a-80b5-3f4f773d6d44.png)

Do I need to be more specific or is this enough? :)

**Comment by xthexder** [comment]
Resolved in version 1.5.2

**Comment by mustaphazorgati** [comment]
Looks good to me. Thank you! :)
