### ISSUE TITLE
Style stopped working for some pages

### ISSUE THREAD

**Issue by MichalPetryka** [xthexder/wide-github#80]
After recent GitHub changes, some pages stopped being full width as shown on the example:
![image](https://github.com/xthexder/wide-github/assets/35800402/6cb8b83b-3231-4a28-b0f3-d5c3e44aadbe)

**Comment by xthexder** [comment]
I've pushed an update that fixes the latest GitHub layout changes (Version 1.6.0)
It should be available on the web stores soon once it passes review.

**Comment by thomasmahoney** [comment]
@xthexder I think either the extension stopped working on, OR github changed the look & feel of, this page: https://github.com/squareup/java/branches/yours

I don't remember exactly how it looked before, but it's ridiculously narrow now. I can only see about 30 characters of my branch names before they get cut off. (and most of my branch names have boilerplate prefixes required by my organization, so I really only get to see about 10-12 characters of "useful data," making it hard to tell which branch is which.)

will 1.6.0 fix this too?

**Comment by xthexder** [comment]
> @xthexder I think either the extension stopped working on, OR github changed the look & feel of, the "your branches" page, e.g. https://github.com/xthexder/wide-github/branches/yours
> 
> I don't remember exactly how it looked before, but it's ridiculously narrow now. I can only see about 30 characters of my branch names before they get cut off. (and most of my branch names have boilerplate prefixes required by my organization, so I really only get to see about 10-12 characters of "useful data," making it hard to tell which branch is which.)
> 
> will 1.6.0 fix this too?

It looks like my latest fixes as far as 1.6.2 don't fix the "Your branches" page. It's another one that's been replaced with a new react layout.
All the CSS class names are random like `jeYfHr` so it's not very easy to figure out good CSS selectors. I'll see if I can get that page fixed for 1.6.3

**Comment by xthexder** [comment]
Both the Chrome and Mozilla extensions have been published. You should be able to pull the latest version if you check for updates.

Make another issue if you find any more broken pages!

**Comment by MichalPetryka** [comment]
![image](https://github.com/xthexder/wide-github/assets/35800402/b7a4b58e-f4ff-4d42-a72c-f56ff69cb01e)
There's still this margin on the left of the page, is this intended?

**Comment by xthexder** [comment]
> There's still this margin on the left of the page, is this intended?

There shouldn't be any margin like that anymore. Can you double-check the extension version you're running?
If you're not on version 1.6.3, you just need to get your browser to download the update.
If not could you send which browser version you're using? Everything looks fine on my end.
