### ISSUE TITLE
File view page textarea is narrow

### ISSUE THREAD

**Issue by JCallicoat** [xthexder/wide-github#81]
Using the userstyle with stylish in firefox, the file page textarea showing the file contents is narrow (50% of the page or so, aligned to the left). I disabled all other userstyles and confirmed the same issue remains.

Here is a link to a file page where I see the issue as well as the line that seems to be causing it. When I edit the style in stylish to comment out this line then the textarea displays at fill width as expected.

https://github.com/xthexder/wide-github/blob/2dc9527d06cf2439b9e1f66e02c5d03179de6a53/wide-github.css#L2

**Comment by xthexder** [comment]
Thanks for the bug report. I'm not really sure if I somehow missed the file viewer this entire time, or if GitHub changed the styling again.
Oh well... Fixed in 1.6.4

**Comment by xthexder** [comment]
Fixes are release, you should be able to get 1.6.4 by checking for extension updates.

**Comment by JCallicoat** [comment]
Thanks for the quick fix!
