### ISSUE TITLE
Violentmonkey script is broken because of wrong quotes in wide-github.user.js

### ISSUE THREAD

**Issue by zrajnai-shapr3d** [xthexder/wide-github#82]
Double quotes are used inside strings starting with double quotes, which causes syntax errors.
The error is repeated in 4 places.

e.g ...="--sticky-pane-height: 100vh;"] ... 
should be
 ...='--sticky-pane-height: 100vh;'] 

(note the double quotes changed to single quotes.

This effective broke the violentmonkey script.

**Comment by xthexder** [comment]
👍 Fixed the build script so it properly escapes double quotes from the CSS.
