### ISSUE TITLE
Support Edge Extension Store

### ISSUE THREAD

**Issue by kieronlanning** [xthexder/wide-github#84]
Can you also upload this incredible plugin to the MS Edge Extension store? https://microsoftedge.microsoft.com/

While the Chrome Store one works, it doesn't synchronise over machines...

**Comment by xthexder** [comment]
The Microsoft Edge Add-ons store has a 19 USD sign-up fee for developers. Unfortunately this doesn't worth it to upload one free extension for a handful of users.

You should be able to install wide-github through userscripts with other extensions like Tampermonkey. That may be able to synchronize across machines.

**Comment by kieronlanning** [comment]
Ooof, didn't realise they were charging! 

Thanks for replying!
