### ISSUE TITLE
Wide GitHub doesn't support new GitHub issues layout

### ISSUE THREAD

**Issue by Shadows-of-Fire** [xthexder/wide-github#86]
GitHub is currently prototyping some [changes](https://github.com/orgs/community/discussions/139935) to the issues page. They're only rolling out these features to select repositories at the moment, but for repositories where this feature is present, Wide GitHub no longer functions.

One example where the new issues page is being shown is the [NeoForge](https://github.com/neoforged/NeoForge/issues) repository.

Screenshot from that repository (2560x1440):
![](https://i.imgur.com/rojZyrQ.png)

**Comment by xthexder** [comment]
This should be fixed in version 1.6.6, which is being reviewed now on the Mozilla / Chrome web stores.

Thanks for reporting!

**Comment by mykaul** [comment]
> This should be fixed in version 1.6.6, which is being reviewed now on the Mozilla / Chrome web stores.
> 
> Thanks for reporting!

Confirmed - thanks for fixing it so quickly!
